name: graph

on:
  schedule:
    - cron: "42 21 * * *"
  push:
    branches:
      - main

env:
  COMMIT_MESSAGE: "📈 update `history.svg` - [Skip Github Action]"

jobs:
  run:
    name: graph

    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, ${{ COMMIT_MESSAGE }})"

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # - name: setup python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.x"
      #     cache: "pip"
      - name: install dependencies
        run: pip install matplotlib

      - name: generate graph
        run: ./graph.py

      - name: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add history.svg
          git commit -m "${COMMIT_MESSAGE}"
          git push
